# -*- coding: utf-8 -*-
"""GenAI-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uEQu63PCle8TwszzR0nxsuy-zJzbTiwL
"""

!pip install gensim

!pip install --upgrade gensim numpy

import gensim
import gensim.downloader as api
from gensim.models import Word2Vec
import numpy as np

medical_corpus = [
    ['patient', 'presents', 'fever', 'cough', 'diagnosed', 'pneumonia'],
    ['doctor', 'prescribes', 'antibiotic', 'therapy', 'recovery'],
    ['surgery', 'performed', 'anesthesia', 'complication', 'risk'],
    ['nurse', 'monitors', 'vital', 'signs', 'blood', 'pressure'],
    ['oncology', 'chemotherapy', 'tumor', 'metastasis', 'remission'],
    ['radiology', 'xray', 'mri', 'scan', 'diagnosis'],
    ['pharmacy', 'dispenses', 'medication', 'dosage', 'side', 'effects'],
    ['emergency', 'trauma', 'resuscitation', 'intubation'],
    ['cardiology', 'ekg', 'arrhythmia', 'stent', 'bypass'],
    ['neurology', 'stroke', 'seizure', 'mri', 'therapy']
] * 50

model = Word2Vec(sentences=medical_corpus, vector_size=50, window=5,
                 min_count=2, sg=1, epochs=20, workers=4)
model.save("medical_word2vec.model")  # Save for reuse
print("Medical Word2Vec trained!")

print("Similar to 'pneumonia':", model.wv.most_similar('pneumonia', topn=5))
print("Similar to 'surgery':", model.wv.most_similar('surgery', topn=5))
print("'doctor' - 'patient' + 'nurse' ≈",
      model.wv.most_similar(positive=['doctor', 'nurse'], negative=['patient'])[0][0])