# -*- coding: utf-8 -*-
"""GenAI-6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RVngWAjY-2l9BoyPmhC5X5yBnV61Ribf
"""

!pip install transformers

!pip install torch

!pip install --upgrade torch transformers

from transformers import pipeline
print("Loading Hugging Face sentiment pipeline...")
sentiment_pipeline = pipeline("sentiment-analysis")
reviews = [
    "The product exceeded my expectations with fast delivery and excellent quality!",
    "Service was poor, late delivery and damaged packaging. Very disappointed.",
    "Average experience - works fine but nothing special about it.",
    "Outstanding customer support resolved my issue within hours!",
    "Overpriced for what it offers, expected much better performance."
]

print("\nSentiment Analysis Results:")
for i, review in enumerate(reviews, 1):
    result = sentiment_pipeline(review)[0]
    label = result['label']
    score = f"{result['score']:.3f}"
    print(f"{i}. '{review[:50]}...' → {label} ({score})")