# -*- coding: utf-8 -*-
"""GenAI-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Uv9L0gU_XM8Dgwuy7VVskDVpjlgrDWx
"""

!pip install gensim

!pip install --upgrade gensim numpy

import ssl
import gensim.downloader as api
ssl._create_default_https_context = ssl._create_unverified_context
model = api.load("word2vec-google-news-300")
print("Model loaded successfully!")

print("\nVector for 'king':",model['king'][:10],"...")
print("Similarity between 'king' and 'queen':",model.similarity('king','queen'))

result_vec = model['king'] - model['man'] + model['woman']
similar_words = model.most_similar(positive=[result_vec], topn=5)
print("\n'king' - 'man' + 'woman' ≈", similar_words[0][0], "with similarity", round(similar_words[0][1], 3))

print("\nOther analogies:")
print("Paris - France + Italy ≈", model.most_similar(positive=['Paris', 'Italy'], negative=['France'])[0][0])
print("boy - child + woman ≈", model.most_similar(positive=['boy', 'woman'], negative=['child'])[0][0])
print("Germany - Berlin + France ≈", model.most_similar(positive=['Germany', 'France'], negative=['Berlin'])[0][0])

custom_vec = model['doctor'] - model['hospital'] + model['school']
print("\n'doctor' - 'hospital' + 'school' nearest:", [word for word, _ in model.most_similar(positive=[custom_vec], topn=3)])

print("\nExploration complete!")